"""Export ThaiBridge's reviewed spellings for the MCP spelling checker.

The checker lives in the mcp-server repo (thaibridge_spelling/) and works from
a JSON snapshot of this app's data rather than calling the app: the app sleeps
on Render's free tier, and a checker that fails whenever it does is no use.
Rerun this when lessons change, then commit the new snapshot there:

    python scripts/export_spelling_snapshot.py ../mcp-server/thaibridge_spelling/data/thaibridge_snapshot.json

What goes in:
  * the 44 consonants from thai_consonants.py — character, name, class and
    initial sound — which the checker uses for first-letter checks and the
    analyser for its breakdown;
  * every Thai/romanisation pair from paiboon_lookup.reviewed_sources(), the
    same sources the /paiboon page searches. The chanting book stays out, as
    it does there: its romanisation is a draft in places.

Unlike the /paiboon index, nothing is de-duplicated across spellings. That
index merges spellings that differ only in tone marks, which is exactly what
hid ถวาย written tà-waai beside tà-wǎai; the checker's consistency report needs
every variant to find those.

The app is imported, so DATABASE_URL is blanked first: an export has no
business on the live database.
"""
import json
import os
import subprocess
import sys
import unicodedata
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.environ['DATABASE_URL'] = ''

import paiboon_lookup  # noqa: E402
import thai_consonants  # noqa: E402


def _pairs(node, label, out):
    """Every dict carrying a thai and a paiboon string, wherever it sits."""
    if isinstance(node, dict):
        thai, rom = node.get('thai'), node.get('paiboon')
        if isinstance(thai, str) and isinstance(rom, str) and thai.strip() and rom.strip():
            english = node.get('english') or node.get('meaning') or ''
            out.append((thai.strip(), unicodedata.normalize('NFC', rom.strip()),
                        english if isinstance(english, str) else '', label))
        for value in node.values():
            _pairs(value, label, out)
    elif isinstance(node, (list, tuple)):
        for item in node:
            _pairs(item, label, out)


def build_snapshot():
    raw = []
    for data, label in paiboon_lookup.reviewed_sources():
        _pairs(data, label, raw)

    # One row per distinct (Thai, romanisation), listing every source that
    # writes it that way, and the first English gloss found.
    rows = {}
    for thai, rom, english, label in raw:
        row = rows.setdefault((thai, rom), {'thai': thai, 'romanisation': rom,
                                            'english': english, 'sources': []})
        if not row['english'] and english:
            row['english'] = english
        if label not in row['sources']:
            row['sources'].append(label)

    consonants = [{'char': c['char'], 'name_thai': c['name_thai'], 'name': c['name'],
                   'meaning': c['meaning'], 'class': c['cls'], 'sound': c['sound'],
                   'obsolete': c['obsolete']}
                  for c in thai_consonants.CONSONANTS]

    try:
        commit = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], cwd=ROOT,
                                capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        commit = 'unknown'

    return {
        'about': ("ThaiBridge AI's reviewed Thai spellings (ThaiBridge Spelling, "
                  "based on Paiboon+). Generated by scripts/export_spelling_snapshot.py "
                  "in thaibridge-ai; do not edit by hand."),
        'exported_at': datetime.now(timezone.utc).isoformat(timespec='seconds'),
        'thaibridge_commit': commit,
        'consonants': consonants,
        'entries': sorted(rows.values(), key=lambda r: (r['thai'], r['romanisation'])),
    }


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    snapshot = build_snapshot()
    out = Path(sys.argv[1])
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(snapshot, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
    print(f"{len(snapshot['entries'])} entries and {len(snapshot['consonants'])} consonants "
          f"from {snapshot['thaibridge_commit']} -> {out}")


if __name__ == '__main__':
    main()
